import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// In order to prevent use code in layout page
import Link from "next/link";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <li><Link href ="/home">Home</Link></li>
            <li> <Link href ="/privacy">Privacy</Link></li>
            <li><Link href ="/about">About</Link></li>
            <li><Link href = "/jobs">Jobs</Link></li>
            <li><Link href ="/contact">Contact</Link></li>
            <li><Link href ="/apply">Apply</Link></li>
<h1 className = 'bg-orange-400'> Governor Sindh IT Class </h1>
    
        {children}
      </body>
    </html>
  );
}
